version: '3'

services:
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: api_project
        ports:
            - "3305:3306"
        volumes:
            - ~/docker/mariadb:/var/lib/mysql
        restart: always