version: '3.8'

services:
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: api_project
        ports:
            - "3306:3306"
        volumes:
            - ~/docker/mariadb:/var/lib/mysql
        restart: always
#
#    web:
#        build:
#            context: ./
#            target: dev
#        volumes:
#            - .:/src
#        command: npm run start
#        ports:
#            - "3000:3000"
#        environment:
#            NODE_ENV: development
#            DEBUG: nodejs-docker-express:*